config/routes.rb
ClassCloud::Application.routes.draw do
  devise_for :users

  
  resources :courses
  resources :users

  root :to => 'welcome#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/course.rb
class Course < ActiveRecord::Base
  # Custom Validation
  validates_date :start_date
  validates_date :end_date
  
  # Relationships
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Custom Validation
  validates :name, :presence => true, :length => {:maximum => 100}, :uniqueness => true
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  # Relationships
  has_and_belongs_to_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find_by_id(params[:id])
  end
  
  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(params[:course])
    
    if @course.save
      flash[:notice] = "Course successfully created."
      redirect_to '/courses'
    else
      flash[:error] = "Course could not be created."
      redirect_to '/courses/new'
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def delete
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  # :root, /welcome/
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Dynamic page titles
  def title(page_title)
    content_for(:title) { page_title }
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :code %><br />
  <%= f.text_field :code %>
</p>

<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :link %><br />
  <%= f.text_field :link %>
</p>

<p>
  <%= f.label :start_date, "Start Date" %><br />
  <%= f.text_field :start_date %>
</p>

<p>
  <%= f.label :end_date, "End Date" %><br />
  <%= f.text_field :end_date %>
</p>

<%= submit_tag "Submit" %>
<% end %>

app/views/courses/edit.html.erb
<% title "Edit #{@course.name}" %>

<h3><%= yield(:title) %></h3>

<%= render :partial => "form" %>

app/views/courses/index.html.erb
<% title "Courses List" %>

<h3><%= yield(:title) %></h3>

<%= link_to "Create Course", new_course_path %><br /><br />

<% @courses.each do |course| %>
  <%= link_to course.name, course_path(course) %>
<% end %>

app/views/courses/new.html.erb
<% title "New Course" %>

<h3><%= yield(:title) %></h3>

<%= render :partial => "form" %>

app/views/courses/show.html.erb
<% title "Show Course #{@course.name}" %>

<h3><%= yield(:title) %></h3>

Name: <%= @course.name %><br />
Code: <%= @course.code %><br />
Description: <%= @course.description %><br />
Start Date: <%= @course.start_date %><br />
End Date: <%= @course.end_date %><br />

<h4>Users associated:</h4>

<% @course.users.each do |user| %>
  <%= link_to user.name, users_path(user) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassCloud - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path  %> or <%= link_to "sign in", new_user_session_path %>
<% end %>

<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:error] %></p>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<% title "Welcome" %>

<h3>Welcome to Class Cloud</h3>